name: Push Updated Plugin Stub to Template

on: push

jobs:
  copy-stub:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@8230315d06ad95c617244d2f265d237a1682d445
      with:
        ref: ${{ github.sha }}
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v41.0.0
      with:
        separator: ","
        files: |
          plugin/*
          
    - name: Is stub changed
      id: changed-stub
      run: |
        STUB_CHANGED="false"
        PATHS=(plugin plugin/decky_plugin.pyi)
        SHA=${{ github.sha }}
        SHA_PREV=HEAD^
        FILES=$(git diff $SHA_PREV..$SHA --name-only -- ${PATHS[@]} | jq -Rsc 'split("\n")[:-1] | join (",")')
        if [[ "$FILES" == *"plugin/decky_plugin.pyi"* ]]; then
          $STUB_CHANGED="true"
          echo "Stub has changed, pushing updated stub"
        else
          echo "Stub has not changed, exiting."
          echo "has_changed=$STUB_CHANGED" >> $GITHUB_OUTPUT
          exit 0
        fi
        echo "has_changed=$STUB_CHANGED" >> $GITHUB_OUTPUT

    - name: Push updated stub
      if: steps.changed-stub.outputs.has_changed == true
      uses: dmnemec/copy_file_to_another_repo_action@bbebd3da22e4a37d04dca5f782edd5201cb97083
      env:
        API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
      with:
        source_file: 'plugin/decky_plugin.pyi'
        destination_repo: 'SteamDeckHomebrew/decky-plugin-template'
        user_email: '11465594+TrainDoctor@users.noreply.github.com'
        user_name: 'TrainDoctor'
        commit_message: 'Updated template with latest plugin stub changes'
